# Generated by Django 5.1.15 on 2026-09-17 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('aspect_ratio', models.CharField(choices=[('16:9', 'Landscape (16:9)'), ('9:16', 'Portrait / Reel (9:16)'), ('1:1', 'Square (1:1)'), ('4:3', 'Classic (4:3)'), ('21:9', 'Cinematic Widescreen (21:9)')], default='16:9', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active In-Progress'), ('rendering', 'Rendering Final Video'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_render', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_render_project', to='media.media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_thumbnail_for', to='media.media')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('prompt', models.TextField(help_text='Generative AI prompt for this scene')),
                ('negative_prompt', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=5, help_text='Scene duration in seconds')),
                ('camera_direction', models.CharField(blank=True, help_text='e.g. Pan left, Dolly zoom, Drone aerial shot, Close-up tracking', max_length=120)),
                ('visual_style', models.CharField(blank=True, help_text='e.g. Cinematic 35mm, Hyperrealistic, Moody neon lighting', max_length=120)),
                ('dialogue', models.TextField(blank=True)),
                ('audio_direction', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_references', models.ManyToManyField(blank=True, related_name='scenes_as_ref', to='media.media')),
                ('characters', models.ManyToManyField(blank=True, related_name='scenes', to='characters.character')),
                ('generated_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_scene', to='media.media')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='projects_pr_owner_i_386ff4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('project', 'order')},
        ),
    ]
