# Generated by Django 5.1.15 on 2026-09-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Signed integer: positive for credit addition, negative for credit reduction')),
                ('transaction_type', models.CharField(choices=[('bonus', 'Bonus / Starter Credits'), ('subscription_credit', 'Monthly Subscription Credits'), ('purchase', 'Credit Pack Purchase'), ('generation_hold', 'Generation Reserved Hold'), ('generation_consume', 'Generation Final Consumption'), ('generation_refund', 'Generation Failure Refund'), ('adjustment', 'Administrative Adjustment'), ('expiration', 'Credit Expiration')], max_length=32)),
                ('balance_before', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('lifetime_earned', models.BigIntegerField(default=0)),
                ('lifetime_spent', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Wallet',
                'verbose_name_plural': 'Credit Wallets',
            },
        ),
    ]
