# Generated by Django 5.1.15 on 2026-09-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditwallet',
            name='purchased_credits',
            field=models.BigIntegerField(default=0, help_text='Non-expiring top-up credits'),
        ),
        migrations.AddField(
            model_name='creditwallet',
            name='subscription_credits',
            field=models.BigIntegerField(default=500, help_text='Monthly refreshing credits'),
        ),
        migrations.AddField(
            model_name='creditwallet',
            name='subscription_renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditwallet',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free Starter (500 Credits)'), ('starter', 'Starter (90,000 Credits/mo)'), ('creator', 'Creator (400,000 Credits/mo + Unlimited)'), ('ultra', 'Ultra (1,000,000 Credits/mo + Unlimited)')], db_index=True, default='free', max_length=20),
        ),
    ]
