# Generated by Django 5.1.15 on 2026-09-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_creditwallet_purchased_credits_and_more'),
        ('generations', '0004_generation_dialogue_generation_is_lip_sync_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference__gt', '')), fields=('external_reference',), name='unique_non_empty_external_reference'),
        ),
    ]
