# Generated by Django 5.1.15 on 2026-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='email_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Badge e.g. 'MOST POPULAR', '20% OFF'", max_length=60),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_all_models_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_early_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_unlimited_fast_models',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_characters',
            field=models.PositiveIntegerField(default=5, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_parallel_images',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_parallel_videos',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, help_text='Paystack Plan Code (e.g. PLN_xxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tagline',
            field=models.CharField(blank=True, help_text="Subtitle e.g. 'For creators making real AI videos'", max_length=160),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='video_models_access',
            field=models.CharField(default='Standard only', max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(default='paystack', max_length=50),
        ),
    ]
