# Generated by Django 5.1.15 on 2026-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_customer_code_subscription_email_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_clone_voices',
            field=models.BooleanField(default=True, help_text='Can create custom neural voice clones'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_voice_profiles',
            field=models.PositiveIntegerField(default=3, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='voice_clone_credit_cost',
            field=models.PositiveIntegerField(default=50, help_text='Credits per voice clone'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='voice_generation_credit_cost',
            field=models.PositiveIntegerField(default=15, help_text='Credits per speech generation'),
        ),
    ]
