# Generated by Django 5.1.15 on 2026-09-17 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_aspect_ratio', models.CharField(default='16:9', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued for Rendering'), ('rendering', 'Stitching Scenes with FFmpeg'), ('completed', 'Render Complete'), ('failed', 'Render Failed')], default='queued', max_length=20)),
                ('render_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
