# Generated by Django 5.1.15 on 2026-09-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0001_initial'),
        ('media', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyjob',
            name='background_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_in_assembly', to='media.media'),
        ),
        migrations.AddField(
            model_name='assemblyjob',
            name='output_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_output', to='media.media'),
        ),
        migrations.AddField(
            model_name='assemblyjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_jobs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='assemblyjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
