# Generated by Django 5.1.15 on 2026-09-17 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('generation_type', models.CharField(choices=[('image', 'Image Generation'), ('video', 'Video Generation'), ('audio', 'Audio Generation'), ('edit', 'Image/Video Edit'), ('upscale', 'Media Upscale')], default='image', max_length=20)),
                ('model_id_snapshot', models.CharField(help_text='Canonical model ID at execution time', max_length=120)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('queued', 'Queued for Dispatch'), ('processing', 'Processing Upstream'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='queued', max_length=20)),
                ('width', models.PositiveIntegerField(default=1280)),
                ('height', models.PositiveIntegerField(default=720)),
                ('duration', models.PositiveIntegerField(default=5, help_text='Duration in seconds (0 for images)')),
                ('aspect_ratio', models.CharField(default='16:9', max_length=10)),
                ('quality', models.CharField(default='standard', max_length=20)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('credits_reserved', models.BigIntegerField(default=0)),
                ('credits_consumed', models.BigIntegerField(default=0)),
                ('external_job_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, help_text='Clean, user-friendly error message', max_length=500)),
                ('admin_error_detail', models.TextField(blank=True, help_text='Full diagnostic traceback or raw upstream provider error payload')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='characters.character')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='providers.aimodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
