# Generated by Django 5.1.15 on 2026-09-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generations', '0001_initial'),
        ('media', '0001_initial'),
        ('projects', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='output_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_generation', to='media.media'),
        ),
        migrations.AddField(
            model_name='generation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='generation',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='providers.aiproviderconfig'),
        ),
        migrations.AddField(
            model_name='generation',
            name='reference_media',
            field=models.ManyToManyField(blank=True, related_name='referenced_in_generations', to='media.media'),
        ),
        migrations.AddField(
            model_name='generation',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='projects.scene'),
        ),
        migrations.AddField(
            model_name='generation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', 'generation_type', 'status', 'created_at'], name='generations_user_id_7a58d7_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['external_job_id'], name='generations_externa_bbd2a9_idx'),
        ),
    ]
