# Generated by Django 5.1.15 on 2026-09-22 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_initial'),
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='audio_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_to_generations', to='media.media'),
        ),
        migrations.AddField(
            model_name='generation',
            name='parent_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_generations', to='generations.generation'),
        ),
    ]
