# Generated by Django 5.1.15 on 2026-09-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0003_generation_audio_track_generation_parent_generation'),
        ('voices', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='dialogue',
            field=models.TextField(blank=True, help_text='Spoken character dialogue script'),
        ),
        migrations.AddField(
            model_name='generation',
            name='is_lip_sync',
            field=models.BooleanField(default=False, help_text='True if generated via unified lip-sync pipeline'),
        ),
        migrations.AddField(
            model_name='generation',
            name='pipeline_stage',
            field=models.CharField(blank=True, help_text='Current execution stage for multi-stage video generation', max_length=100),
        ),
        migrations.AddField(
            model_name='generation',
            name='uses_native_veo_audio',
            field=models.BooleanField(default=False, help_text='True if audio was natively generated by Google Veo without ElevenLabs'),
        ),
        migrations.AddField(
            model_name='generation',
            name='voice_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='voices.voiceprofile'),
        ),
    ]
