# Generated by Django 5.1.15 on 2026-09-17 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True, help_text='Short bio or background')),
                ('appearance_description', models.TextField(help_text='Detailed visual traits: facial structure, hair color/style, eye color, age, build')),
                ('clothing_description', models.TextField(blank=True, help_text='Standard outfit or wardrobe style cues')),
                ('personality', models.TextField(blank=True, help_text='Behavioral and expression traits')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='characters/avatars/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
