# Generated by Django 5.1.15 on 2026-09-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='reference_images',
            field=models.ManyToManyField(blank=True, related_name='character_reference_for', to='media.media'),
        ),
        migrations.AddField(
            model_name='character',
            name='voice_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_voice_for', to='media.media'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('owner', 'name')},
        ),
    ]
