# Generated by Django 5.1.15 on 2026-09-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
        ('voices', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='voice_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='voices.voiceprofile'),
        ),
    ]
