# Generated by Django 5.1.15 on 2026-09-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy (Operational)'), ('degraded', 'Degraded (High Latency/Timeouts)'), ('offline', 'Offline (Unavailable)')], default='healthy', max_length=20)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.PositiveIntegerField(default=1200)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Name of environment variable storing secret key', max_length=100)),
                ('webhook_secret_env_var', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Config',
                'verbose_name_plural': 'AI Provider Configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='Canonical model identifier sent to adapter', max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('modality', models.CharField(choices=[('video', 'Video Generation'), ('image', 'Image Generation'), ('audio', 'Audio / Voice'), ('multimodal', 'Multimodal')], default='video', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=list, help_text="List of capability flags: ['t2v', 'i2v', 'audio', 'character_ref', 'multishot', 'upscale']")),
                ('max_duration', models.PositiveIntegerField(default=10, help_text='Max video duration in seconds (0 for images)')),
                ('supported_resolutions', models.JSONField(blank=True, default=list, help_text="e.g. ['720p', '1080p', '4k']")),
                ('supported_aspect_ratios', models.JSONField(blank=True, default=list, help_text="e.g. ['16:9', '9:16', '1:1']")),
                ('supports_audio', models.BooleanField(default=False)),
                ('supports_image_reference', models.BooleanField(default=False)),
                ('supports_video_reference', models.BooleanField(default=False)),
                ('supports_character_reference', models.BooleanField(default=False)),
                ('credit_cost_fixed', models.PositiveIntegerField(default=50, help_text='Fixed base credit cost per generation')),
                ('credit_cost_per_second', models.PositiveIntegerField(default=50, help_text='Additional credit cost per video second')),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Higher value = prioritized by model router')),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='providers.aiproviderconfig')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['-priority', 'display_name'],
            },
        ),
    ]
