import uuid
from django.db import models
from django.conf import settings

class Generation(models.Model):
    """Universal AI generation request tracking image, video, and audio tasks."""
    GENERATION_TYPES = [
        ('image', 'Image Generation'),
        ('video', 'Video Generation'),
        ('audio', 'Audio Generation'),
        ('edit', 'Image/Video Edit'),
        ('upscale', 'Media Upscale'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending Approval'),
        ('queued', 'Queued for Dispatch'),
        ('processing', 'Processing Upstream'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('cancelled', 'Cancelled'),
        ('refunded', 'Refunded'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    correlation_id = models.UUIDField(default=uuid.uuid4, db_index=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='generations'
    )
    project = models.ForeignKey(
        'projects.Project',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='generations'
    )
    scene = models.ForeignKey(
        'projects.Scene',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='generations'
    )
    generation_type = models.CharField(max_length=20, choices=GENERATION_TYPES, default='image')
    provider = models.ForeignKey(
        'providers.AIProviderConfig',
        on_delete=models.PROTECT,
        related_name='generations'
    )
    model = models.ForeignKey(
        'providers.AIModel',
        on_delete=models.PROTECT,
        related_name='generations'
    )
    model_id_snapshot = models.CharField(max_length=120, help_text="Canonical model ID at execution time")
    
    # Prompt specification
    prompt = models.TextField()
    negative_prompt = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='queued', db_index=True)
    
    # Output parameters
    width = models.PositiveIntegerField(default=1280)
    height = models.PositiveIntegerField(default=720)
    duration = models.PositiveIntegerField(default=5, help_text="Duration in seconds (0 for images)")
    aspect_ratio = models.CharField(max_length=10, default="16:9")
    quality = models.CharField(max_length=20, default="standard")
    seed = models.BigIntegerField(null=True, blank=True)

    # Reference assets
    reference_media = models.ManyToManyField(
        'media.Media',
        blank=True,
        related_name='referenced_in_generations'
    )
    character = models.ForeignKey(
        'characters.Character',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='generations'
    )

    # Output media asset
    output_media = models.OneToOneField(
        'media.Media',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='source_generation'
    )

    # Optional parent generation & attached audio track
    parent_generation = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='child_generations'
    )
    audio_track = models.ForeignKey(
        'media.Media',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='attached_to_generations'
    )

    # 1-Step Unified Lip-Sync & Voice Conditioning
    is_lip_sync = models.BooleanField(default=False, help_text="True if generated via unified lip-sync pipeline")
    dialogue = models.TextField(blank=True, help_text="Spoken character dialogue script")
    voice_profile = models.ForeignKey(
        'voices.VoiceProfile',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='generations'
    )
    pipeline_stage = models.CharField(
        max_length=100,
        blank=True,
        help_text="Current execution stage for multi-stage video generation"
    )
    uses_native_veo_audio = models.BooleanField(
        default=False,
        help_text="True if audio was natively generated by Google Veo without ElevenLabs"
    )

    # Credit accounting
    credits_reserved = models.BigIntegerField(default=0)
    credits_consumed = models.BigIntegerField(default=0)

    # External orchestration
    external_job_id = models.CharField(max_length=255, blank=True, db_index=True)
    provider_response = models.JSONField(default=dict, blank=True)
    
    # Error handling
    error_message = models.CharField(
        max_length=500,
        blank=True,
        help_text="Clean, user-friendly error message"
    )
    admin_error_detail = models.TextField(
        blank=True,
        help_text="Full diagnostic traceback or raw upstream provider error payload"
    )

    is_favorite = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'generation_type', 'status', 'created_at']),
            models.Index(fields=['external_job_id']),
        ]

    def __str__(self):
        return f"{self.get_generation_type_display()} [{self.status}] - {self.user.email} ({self.id})"

    @property
    def is_in_progress(self) -> bool:
        return self.status in ('queued', 'processing')

    @property
    def latest_audio(self):
        """Fetch the most recent audio media attached or generated for this video."""
        if self.audio_track:
            return self.audio_track
        child = self.child_generations.filter(generation_type='audio', status='completed').order_by('-created_at').first()
        if child and child.output_media:
            return child.output_media
        return None

    @property
    def is_synthesizing_audio(self) -> bool:
        """Check if an audio synthesis job is currently processing for this generation."""
        return self.child_generations.filter(generation_type='audio', status__in=['queued', 'processing']).exists()
