# Generated by Django 5.1.15 on 2026-09-23 15:30

import apps.voices.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Tone, cadence, and vocal persona description')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral / Ambiguous'), ('custom', 'Custom Character')], default='neutral', max_length=20)),
                ('accent', models.CharField(blank=True, default='Neutral', max_length=60)),
                ('language', models.CharField(default='en', max_length=40)),
                ('provider', models.CharField(default='elevenlabs', help_text='Upstream engine (elevenlabs, fal, mock)', max_length=40)),
                ('provider_voice_id', models.CharField(blank=True, db_index=True, help_text='Canonical remote voice ID (e.g. ElevenLabs voice_id)', max_length=120)),
                ('status', models.CharField(choices=[('ready', 'Ready for Synthesis'), ('processing', 'Cloning Neural Weights'), ('failed', 'Cloning Failed')], db_index=True, default='ready', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('consent_confirmed', models.BooleanField(default=True, help_text='User affirmed legal consent and usage rights for this voice')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_for_voice', to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to=apps.voices.models.voice_sample_upload_path)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voice_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='voices.voiceprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
